name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose the Python version you want to use

      - name: Install dependencies
        run: pip install PyGithub

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          python - << EOF
          import os
          from github import Github

          def create_github_release():
              # Get GitHub token from environment variables
              github_token = os.environ.get('GITHUB_TOKEN')

              # Create a GitHub instance
              g = Github(github_token)

              # Get the repository
              repo = g.get_repo(os.environ.get('GITHUB_REPOSITORY'))

              # Create a release
              release = repo.create_git_release(
                  tag=os.environ.get('GITHUB_REF'),
                  name=os.environ.get('GITHUB_REF'),
                  draft=True  # Set draft to True to create a draft release
              )

              print(f"Created draft release {release.title} ({release.html_url})")

          if __name__ == "__main__":
              create_github_release()
          EOF
